basePath: /api
definitions:
  model.Author:
    properties:
      firstname:
        type: string
      id:
        type: string
      secondname:
        type: string
    required:
    - firstname
    - secondname
    type: object
  model.CreateAuthor:
    properties:
      firstname:
        type: string
      secondname:
        type: string
    required:
    - firstname
    - secondname
    type: object
  model.GetAllAuthor:
    properties:
      author:
        items:
          $ref: '#/definitions/model.Author'
        type: array
      count:
        type: integer
    type: object
  model.Response:
    properties:
      data: {}
      message:
        type: string
    type: object
host: http://localhost:7676
info:
  contact:
    email: umarov.doniyor.2002@gmail.com
    name: 404th
    url: http://t.me/myevenway
  description: BookStore
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Book Store
  version: "1.0"
paths:
  /author:
    get:
      consumes:
      - application/json
      description: get all authors
      operationId: get-all-authors
      parameters:
      - description: limit
        in: query
        name: limit
        type: string
      - description: offset
        in: query
        name: offset
        type: string
      - description: search
        in: query
        name: search
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: All authors
          schema:
            allOf:
            - $ref: '#/definitions/model.Response'
            - properties:
                data:
                  $ref: '#/definitions/model.GetAllAuthor'
              type: object
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/model.Response'
            - properties:
                error:
                  $ref: '#/definitions/model.Response'
              type: object
        "404":
          description: Not Found
          schema:
            allOf:
            - $ref: '#/definitions/model.Response'
            - properties:
                error:
                  $ref: '#/definitions/model.Response'
              type: object
        "500":
          description: Server Error
          schema:
            allOf:
            - $ref: '#/definitions/model.Response'
            - properties:
                error:
                  $ref: '#/definitions/model.Response'
              type: object
      summary: get all authors
      tags:
      - author
    post:
      consumes:
      - application/json
      description: create author
      operationId: create-author
      parameters:
      - description: Create Author
        in: body
        name: CreateAuthor
        required: true
        schema:
          $ref: '#/definitions/model.CreateAuthor'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.Response'
      summary: create author
      tags:
      - author
  /author/{id}:
    get:
      consumes:
      - application/json
      description: get an author
      operationId: get-an-author
      parameters:
      - description: Get an author
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.Response'
        "404":
          description: Not found
          schema:
            $ref: '#/definitions/model.Response'
      summary: get an author
      tags:
      - author
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
